apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workshop
resources:
  - ../../base
images:
  - name: shwetamg20/three-tier-backend
    newTag: 2c49e9d5b29e8f7b96204806fe5b8c4da3e9f5b2
  - name: shwetamg20/three-tier-frontend
    newTag: initial