apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workshop
resources:
  - ../../base
images:
  - name: shwetamg20/three-tier-backend
    newTag: initial
  - name: shwetamg20/three-tier-frontend
    newTag: initial

    